support proc default values in ruby 3.2
Fixes:
```
NoMethodError: undefined method `=~' for #<Proc:..
```

As
https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues/1032
explains `=~` [was removed](https://bugs.ruby-lang.org/issues/15231) from Proc.

`Proc` are handled by [this line of
code](https://github.com/rails/rails/blob/v7.0.4.2/activerecord/lib/active_record/connection_adapters/abstract/quoting.rb#L96)

The solution is to add a check and call `~=` only when `value` is a `String`.

I took the oportunity to also follow rubocop performance suggestions
```
Performance/StringInclude: Use String#include? instead of a regex match
with literal-only pattern.
```
Got the idea from postgresql adapter
(https://github.com/rails/rails/commit/5726b1d1d7665c33830ad114f45258ecf772b7b6#diff-d8e4ab5c8c59df4fc1bc85457af0d07b88bd842a287233617a97ad2436fcb842R120)